export const SCNCableMetrics = {
  radius: 1.45,
  radialSegments: 18,
  reliefEase: 0.85
} as const

export const SCNLightningMetrics = {
  tabWidth: 6.7,
  tabThickness: 1.5,
  tabLength: 7.7,
  tabCorner: 0.74,
  tabSegments: 6,
  contactCount: 8,
  contactWidth: 0.48,
  contactLength: 3.9,
  contactPitch: 0.68,
  contactInset: 1.9,
  contactRelief: 0.015,
  contactBedWidth: 5.9,
  contactBedLength: 5.35,
  contactBedInset: 1.18,
  contactBedThickness: 0.06,
  housingWidth: 10.9,
  housingThickness: 5.6,
  housingLength: 11.6,
  housingCorner: 2.2,
  housingSegments: 5,
  shoulderLength: 1.15,
  shoulderInset: 0.5,
  shoulderCorner: 1,
  housingSeamWidth: 0.16,
  reliefLength: 7.2,
  reliefRootRadius: 2.05,
  reliefSegments: 24
} as const

export const SCNUSBPlugMetrics = {
  shellWidth: 12.1,
  shellHeight: 4.6,
  shellLength: 11.6,
  shellCorner: 0.32,
  shellSegments: 3,
  overmoldWidth: 15.4,
  overmoldHeight: 7.6,
  overmoldLength: 13.2,
  overmoldCorner: 1.55,
  overmoldSegments: 6,
  overmoldRelief: 1.1,
  overmoldSeat: 0.35,
  reliefLength: 13,
  reliefRootRadius: 2.95,
  reliefSegments: 24,
  markWidth: 7.6,
  markInset: 6.4,
  markLift: 0.03,
  tongueWidth: 10.4,
  tongueLength: 7.8,
  tongueThickness: 1.05,
  tongueInset: 2.4,
  contactCount: 4,
  contactWidth: 1.05,
  contactLength: 4.8,
  contactPitch: 2.3,
  contactLift: 0.04,
  latchWidth: 2.2,
  latchLength: 1.45,
  latchInset: 5.2
} as const

export const SCNAdapterMetrics = {
  cubeWidth: 33,
  cubeHeight: 33,
  cubeDepth: 29,
  cubeCorner: 4.4,
  cubeSegments: 8,
  seamOffset: 11.4,
  seamWidth: 0.44,
  seamDepth: 0.17,
  seamSteps: 4,
  seatClearance: 2,
  pinRadius: 2.4,
  pinLength: 19,
  pinGap: 19,
  pinChamfer: 0.85,
  pinSegments: 22,
  portWidth: 12.7,
  portHeight: 5.2,
  portCorner: 0.5,
  portDepth: 12.2,
  portSegments: 3
} as const

export const SCNSocketMetrics = {
  bodyLength: 194,
  bodyWidth: 72,
  bodyCorner: 28,
  bodyHeight: 40,
  cornerSegments: 12,
  crownInset: 4.5,
  crownDepth: 6.4,
  crownSteps: 8,
  upperInset: 0.3,
  seamHeight: 25,
  seamGap: 0.36,
  baseTuck: 4.4,
  baseDepth: 5.2,
  baseSteps: 6,
  outletCount: 3,
  outletPitch: 60,
  firstOutletOffset: 37,
  wellRadius: 25,
  chamferWidth: 2.3,
  chamferDepth: 2.2,
  wellDepth: 9,
  wellSegments: 72,
  pinHoleRadius: 2.65,
  pinHoleGap: 19,
  pinHoleDepth: 19,
  pinHoleSegments: 26,
  sleeveRadius: 2.42,
  sleeveInset: 3.2,
  sleeveLength: 5.5,
  earthArc: 0.7,
  earthHeight: 3.7,
  earthThickness: 0.7,
  earthDepth: 4.6,
  earthSegments: 24,
  legendLift: 0.03
} as const
